services:
  db:
    image: mysql:8.4
    container_name: app_db_laravel_react
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gigi
      MYSQL_DATABASE: app
      MYSQL_USER: gigi
      MYSQL_PASSWORD: gigi
    networks:
      - app_laravel_react

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin_laravel_react
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: gigi
      PMA_PASSWORD: gigi
    networks:
      - app_laravel_react

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel_app
    restart: on-failure
    volumes:
      - ./project:/var/www
      - /var/www/vendor
      - ./docker/php/custom-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    ports:
      - "8741:8000"
      - "5173:5173"
    depends_on:
      - db
      - redis
    networks:
      - app_laravel_react

  react-app:
    build:
      context: ./project/resources/crud-react-vite
      dockerfile: Dockerfile
    container_name: react_app
    restart: on-failure
    ports:
      - "4200:4200"
    volumes:
      - ./project/resources/crud-react-vite:/app
      - /app/node_modules
    environment:
      VITE_BASE_URI: http://localhost:4200
      NODE_ENV: development
    networks:
      - app_laravel_react
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: app_redis
    networks:
      - app_laravel_react

networks:
  app_laravel_react:
    driver: bridge

volumes:
  db-data:
